### ISSUE TITLE
Error in rval[i, j, drop = drop., ...] : invalid subscript type 'list'

### ISSUE THREAD

**Issue by mrasska** [nipfpmf/eventstudies#19]
Hi everyone, 

I tried to run an event study for an analysis and I got the following error : "Error in rval[i, j, drop = drop., ...] : invalid subscript type 'list'". 
I am not familiar with the method and this might be a rooky mistake. 

Here is my code: 
```
df_first_test <- subset(df_first, select=c('channel', 'date_formated', 'id_0'))

info <- df_first_test%>%
  pivot_wider(names_from = channel, values_from = id_0)

# info is a dataframe composed of 21 rows (weeks) and 50064 columns (channels).

info <- read.zoo(info, header=TRUE, index.column = 1, format = "%Y-%m-%d")

df_treatment_time=subset(df_first, select=c('channel'))
colnames(df_treatment_time)[1] ="name"
df_treatment_time$when='2017-03-26'
df_treatment_time$when <- as.Date(df_treatment_time$when, "%Y-%m-%d")

es <-eventstudy(firm.returns = info,
                event.list = df_treatment_time,
                event.window = 9,
                type = 'None', 
                to.remap = TRUE,
                remap = 'cumsum',
                inference = TRUE,
                inference.strategy = 'bootstrap')
plot(es)
```
Here is a snapshot of the error: 
![image](https://github.com/xKDR/eventstudies/assets/45817556/d627fcff-3a7e-4102-9416-226870d4d438)

Here are some information about my datasets : 
_Info dataset **(prior to transformation into a zoo object)**_
![image](https://github.com/xKDR/eventstudies/assets/45817556/af6cf80e-7014-430b-904e-158e084c7ec2)

_Info data **(post transformation into zoo object)**_
![image](https://github.com/xKDR/eventstudies/assets/45817556/70e8cb47-4c85-4bc0-a045-ee7d7d787f3e)

_df_treatment_time dataset_
![image](https://github.com/xKDR/eventstudies/assets/45817556/f918b2f5-76a2-4b77-b5ce-eaa9d319a313)

I thank you in advance for your time and help.
Maria

Edit : I think it's my zoo dataset which causes the issue 😓

**Comment by chiraganand** [comment]
I am hoping you have been able to sort this out.

Duplicate of #6. Solution at: https://github.com/xKDR/eventstudies/issues/6#issuecomment-631949616
