### ISSUE TITLE
Error in rval[i, j, drop = drop., ...] : subscript out of bounds

### ISSUE THREAD

**Issue by matguidi** [nipfpmf/eventstudies#6]
Hello, I am trying to estimate an event study model and estimation runs fine when I use `type = "None"`. When I try to use `type = "marketModel"` and I submit market returns as

`model.args = list(
                   market.returns = data$variable)`

I get the error `Error in rval[i, j, drop = drop., ...] : subscript out of bounds`

Looking at the code of the function `eventstudy` I cannot see when this object is used. I thought the problem might be the different dates or different number of rows between `firm.returns` and `market.returns`, but I have made sure they have the same dates and the same number of rows, so I am a bit clueless as to what the problem is. 

Any help in debugging this error is appreciated.

**Comment by chiraganand** [comment]
Hi @matguidi, you need to use `drop = FALSE` in your function call to use a single series. From the man page of `eventstudy()` function:

>      “firm.returns” can contain a single series also. To study a single
>      series, use ‘[’ with ‘drop = FALSE’ to subset the data set. See
>      ‘phys2eventtime’ for more details.
>

**Comment by matguidi** [comment]
Thanks for your reply, but I'm not sure I understand what you mean. I don't have a single series for `firm.returns` (actually I have 26). I have a single series for `market.returns`, though. Should the option `drop = FALSE` be used in this case too? And where should it be specified?

I have tried
`model.args = list(
                   market.returns = data[, "variable"],
                   drop = FALSE)
                 )`

but I get the same error.

**Comment by chiraganand** [comment]
>
> model.args = list( market.returns = data[, "variable"], drop = FALSE) )
>

`drop` is an argument to `[`. Try:  `market.returns = data[, "variable",
drop = FALSE]`. Considering `data` is a `zoo` object.
